### PR TITLE
:trollface:

### PR DESCRIPTION
**Pull request by megasssdev**
:trollface::trollface::trollface:

### CODE REVIEW

**Comment by Jsa010** [comment]
k

**Comment by Jsa010** [comment]
stop

**Comment by megasssdev** [comment]
> stop

?

**Comment by Jsa010** [comment]
u inserted troll

**Comment by megasssdev** [comment]
> u inserted troll

pull requests are not useful here so i dont think it matters

**Comment by Jsa010** [comment]
ok

**Comment by Pico8430** [comment]
they actually merged a grammar fix on the readme file

**Pull request merged**
