### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cherryiguess**
says which day it was removed (for new people i guess) and adds an awesome image for rule 3

### CODE REVIEW

**Comment by cherryiguess** [comment]
> says which day discussions were removed (for new people i guess) and adds an awesome image for rule 3

**Review by Pico8430 — APPROVED** [review]
This change on README.md is actually cooler than the other one.

**Review by DaveFan19 — APPROVED** [review]

**Comment by mayo78** [comment]
no!!!!!!!!

**Comment by mayo78** [comment]
cahgen my mined

**Comment by mayo78** [comment]
actually

**Comment by mayo78** [comment]
nvm

**Pull request closed without merging**
